const data = {
    products: [
        {
            _id: '1',
            name: 'Valorant Agents 1',
            category: 'skin',
            image: '/images/image1.png',
            price: 120,
            brand: 'Epic Games',
            rating: 4.5,
            numReviews: 10,
            description: 'Premium Valorant Agents',
        },
        {
            _id: '2',
            name: 'Valorant Agents 2',
            category: 'skin',
            image: '/images/image2.png',
            price: 120,
            brand: 'Epic Games',
            rating: 3,
            numReviews: 10,
            description: 'Premium Valorant Agents',
        },
        {
            _id: '3',
            name: 'Valorant Agents 3',
            category: 'skin',
            image: '/images/image3.png',
            price: 120,
            brand: 'Epic Games',
            rating: 4,
            numReviews: 10,
            description: 'Premium Valorant Agents',
        },
        {
            _id: '4',
            name: 'Valorant Agents 4',
            category: 'skin',
            image: '/images/image4.png',
            price: 120,
            brand: 'Epic Games',
            rating: 5,
            numReviews: 10,
            description: 'Premium Valorant Agents',
        },
        {
            _id: '5',
            name: 'Valorant Agents 5',
            category: 'skin',
            image: '/images/image5.png',
            price: 120,
            brand: 'Epic Games',
            rating: 2.5,
            numReviews: 10,
            description: 'Premium Valorant Agents',
        },
        {
            _id: '6',
            name: 'Valorant Agents 6',
            category: 'skin',
            image: '/images/image6.png',
            price: 120,
            brand: 'Epic Games',
            rating: 3.5,
            numReviews: 10,
            description: 'Premium Valorant Agents',
        },
    ],
};

export default data;
